blank_issues_enabled: true
contact_links:
    - name: General Question
      url: https://github.com/sgeraldes/waveterm/discussions
      about: Have a question on something? Start a new discussion thread.
    - name: Review open issues
      url: https://github.com/sgeraldes/waveterm/issues
      about: Please check if your issue isn't already there.
    - name: Upstream Reference
      url: https://github.com/wavetermdev/waveterm
      about: Original upstream project for reference and credit.
